name: Integration Tests
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
    integrations-tests:
      strategy:
        matrix:
          os: [macos-latest, ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - uses: docker-practice/actions-setup-docker@master
        - run: |
               set -x
               docker version
               python3 -m pip install --upgrade pip
               pip3 install setuptools wheel twine
               pip3 install .
               fr check
               fr provision -c ls
               fr view
               fr remove freshenv_1
               fr clean
               fr flavours
               fr build testenv
               echo "[testenv]" >> ~/.freshenv/freshenv
               echo "base=ubuntu" >> ~/.freshenv/freshenv
               echo "install=apt update -y && apt upgrade -y && apt install snapd -y" >> ~/.freshenv/freshenv
               echo "cmd=bash" >> ~/.freshenv/freshenv
               fr build testenv
               fr cloud config
